### ISSUE TITLE
Do you need this code?

### ISSUE THREAD

**Issue by avermeulen** [GarethW1994/loop_for_awhile#3]
@GarethW1994 

What does `getMax` do?

``` javascript

      var  splitSentence = sentence.split(" ");
      var keepSentence = [];

      // what does this line do?
      var getMax = Math.max(parseInt(splitSentence.length));

      var longestWord;

```

**Comment by williamsgareth** [comment]
getMax is a variable that stores the output of the highest length in the split and then convert it to a integer as well.

**Comment by avermeulen** [comment]
Are you sure? 😀 @GarethW1994

**Comment by williamsgareth** [comment]
To my knowledge it returns the highest value in an array or series of numbers :? I could be wrong @avermeulen

**Comment by avermeulen** [comment]
@GarethW1994 try it out and tell me what exactly it is doing please.

**Comment by williamsgareth** [comment]
var getMax = Math.max(50, 80);

console.log(getMax);

That is how I tried to test it and it display the highest number which is 80 as the output.

but if I add variables in there for  example:

var num1 = 80;
var num2 = 50;

var getMax = Math.max(parseInt(num1, num2));

console.log(getMax);

I get the output of (NaN) which means it is not a number. So using parseInt doesn't seem to convert the two variables to integer or am I missing something.

**Comment by williamsgareth** [comment]
Or on second thought I can simplify that. I will review my code and remove that line. After testing it, it doesn't give me the desired output. Thanks for pointing that out Andre.

**Comment by avermeulen** [comment]
Ok that was my point exactly ;-)
